import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * DB_DESIGN.MD §6, §7.2 — the counter rows behind customer and sale numbers.
 *
 * These are deliberately **not** PostgreSQL sequences. `nextval()` is
 * non-transactional, so a rolled-back transaction burns the number and leaves a
 * gap; a counter row under `SELECT … FOR UPDATE` rolls back with the
 * transaction. Gapless invoice numbering is the safer default for a system
 * whose output is financial documents — a missing invoice number invites the
 * question of what was deleted, and answering it costs more than the lock ever
 * will (BR-46).
 *
 * The contention is theoretical at this scale: the lock is held for
 * microseconds, and NFR-13 describes tens of thousands of sales, not thousands
 * per second. If sale creation ever does become a throughput bottleneck, the
 * correct fix is a sequence *plus* an explicit business decision that gaps are
 * acceptable — not a quiet swap.
 *
 * Both tables hold exactly one row, at id = 1. The CHECK states that in the
 * schema; a stray second row would otherwise silently split the series.
 *
 * `sale_id_sequences.date` is vestigial — written once, never read, left from
 * per-day numbering. It carries no UNIQUE constraint here (H-15).
 */
export class Sequences1756000000013 implements MigrationInterface {
  name = 'Sequences1756000000013';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE customer_id_sequences (
        id          bigint  NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        last_serial integer NOT NULL DEFAULT 0,
        CONSTRAINT customeridsequence_singleton CHECK (id = 1),
        CONSTRAINT customeridsequence_non_negative CHECK (last_serial >= 0)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE sale_id_sequences (
        id           bigint  NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        date         date    NULL,        -- vestigial (§17)
        sequence_num integer NOT NULL DEFAULT 0,
        CONSTRAINT saleidsequence_singleton CHECK (id = 1),
        CONSTRAINT saleidsequence_non_negative CHECK (sequence_num >= 0)
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS sale_id_sequences`);
    await queryRunner.query(`DROP TABLE IF EXISTS customer_id_sequences`);
  }
}
