import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * FR-02 / DB_DESIGN.MD §6 — the largest domain, and the one where the
 * invariants matter most.
 *
 * Three things here deserve to be understood rather than skimmed:
 *
 * 1. **`sale_not_overpaid` is how BR-09 becomes real.** Overpayment is a
 *    cross-row rule and cross-row rules cannot be a CHECK. The trick is to
 *    materialise the sum into `amount_paid` (maintained by the trigger in
 *    migration 014), which turns it into a single-row comparison the database
 *    can enforce absolutely.
 *
 * 2. **`sale_finalized_has_timestamp` is a biconditional.** A finalised sale
 *    must have a finalisation time, *and* a sale with one must be finalised.
 *    The second half is what stops the "reverted to draft" path (FR-02.6.2)
 *    leaving a stale `finalized_at` behind, which would corrupt BR-16's FIFO
 *    ordering.
 *
 * 3. **`status_code` is a denormalised copy, and it is not optional.** Both the
 *    constraint above and the two partial indexes read the status from the row
 *    itself, and neither a CHECK nor an index predicate can join. One composite
 *    foreign key onto `statuses(id, scope, code)` holds all three columns
 *    together so the copy cannot drift (BR-63).
 */
export class Sales1756000000010 implements MigrationInterface {
  name = 'Sales1756000000010';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE sales (
        id              bigint        NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        sale_number     varchar(100)  NOT NULL UNIQUE,  -- RD-01, one global series (BR-46)
        shop_id         bigint        NOT NULL          -- BR-49
          REFERENCES shops(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        customer_id     bigint        NOT NULL
          REFERENCES customers(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
        status_id       bigint        NOT NULL,
        status_scope    varchar(20)   NOT NULL DEFAULT 'sale',
        status_code     varchar(30)   NOT NULL,          -- denormalised (BR-63)
        notes           text          NOT NULL DEFAULT '',
        total_amount    numeric(14,2) NOT NULL DEFAULT 0, -- derived (migration 014)
        amount_paid     numeric(14,2) NOT NULL DEFAULT 0, -- derived (migration 014)
        created_by_id   bigint        NULL REFERENCES users(id) ON DELETE SET NULL,
        finalized_by_id bigint        NULL REFERENCES users(id) ON DELETE SET NULL,
        finalized_at    timestamptz   NULL,
        created_at      timestamptz   NOT NULL DEFAULT now(),
        updated_at      timestamptz   NOT NULL DEFAULT now(),

        CONSTRAINT sale_totals_non_negative
          CHECK (total_amount >= 0 AND amount_paid >= 0),
        CONSTRAINT sale_not_overpaid                      -- BR-09
          CHECK (amount_paid <= total_amount),
        CONSTRAINT sales_status_scope_pinned              -- BR-58
          CHECK (status_scope = 'sale'),
        CONSTRAINT fk_sales_status                        -- BR-63
          FOREIGN KEY (status_id, status_scope, status_code)
          REFERENCES statuses(id, scope, code)
          ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
        CONSTRAINT sale_finalized_has_timestamp           -- BR-07
          CHECK ((status_code = 'finalized') = (finalized_at IS NOT NULL)),

        -- BR-50: composite target so a line can pin sale and shop together
        CONSTRAINT uq_sales_id_shop UNIQUE (id, shop_id)
      )
    `);

    // BR-53: the sale's customer must belong to the sale's shop.
    await queryRunner.query(`
      ALTER TABLE sales ADD CONSTRAINT fk_sale_customer_shop
        FOREIGN KEY (customer_id, shop_id) REFERENCES customers(id, shop_id)
        ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
    `);

    await queryRunner.query(
      `CREATE INDEX idx_sale_customer ON sales (customer_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_sale_created_by ON sales (created_by_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_sale_created_at ON sales (created_at DESC)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_sale_status_created ON sales (status_code, created_at DESC)`,
    );

    /**
     * The single most valuable index in this schema. The customer payment
     * allocator (BR-16) locks and walks every finalised sale for one customer
     * in finalisation order; without this that is a sequential scan **while
     * holding row locks**, which turns a slow query into a lock-contention
     * incident under concurrency.
     *
     * Column order `(customer_id, finalized_at, id)` is deliberate: the leading
     * column serves the WHERE and the remaining two supply the ORDER BY in
     * index order, so the sort disappears entirely rather than merely getting
     * cheaper. Reordering these keeps the filter but brings the sort back.
     */
    await queryRunner.query(
      `CREATE INDEX idx_sale_fifo
         ON sales (customer_id, finalized_at, id) WHERE status_code = 'finalized'`,
    );
    // FR-01.2: "today's finalised sales", on every dashboard load.
    await queryRunner.query(
      `CREATE INDEX idx_sale_finalized_at
         ON sales (finalized_at) WHERE status_code = 'finalized'`,
    );
    // FR-11.5.1 / FR-11.5.2: shop-filtered sales list and dashboard.
    await queryRunner.query(
      `CREATE INDEX idx_sales_shop_created ON sales (shop_id, created_at DESC)`,
    );

    /**
     * `sale_items` carries a `shop_id` of its own so that two composite foreign
     * keys can pin it from both directions at once:
     *
     *   sale_items(sale_id, shop_id)           -> sales(id, shop_id)
     *   sale_items(inventory_item_id, shop_id) -> inventory_items(id, shop_id)
     *
     * The first says *this line's shop is its sale's shop*; the second says
     * *this line's shop is its product's shop*. Both hold only when the sale
     * and the product are in the same shop — which is BR-50, enforced by
     * ordinary referential integrity rather than a trigger. No trigger to
     * maintain, no ordering hazard, and foreign keys cannot rot.
     *
     * The column is denormalised, and that is the price. Copy it from the sale
     * on insert; never let a user choose it.
     *
     * `line_total` is a stored generated column rather than the BEFORE trigger
     * §11 describes. §11 note 4 recommends exactly this on NestJS — the legacy
     * stack could not use it only because Django emits every field in its
     * INSERT. It is mapped read-only in the entity.
     */
    await queryRunner.query(`
      CREATE TABLE sale_items (
        id                bigint        NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        sale_id           bigint        NOT NULL
          REFERENCES sales(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
        shop_id           bigint        NOT NULL,     -- BR-50; carried, not chosen
        item_type_id      bigint        NOT NULL,     -- FR-12.8
        item_type_code    varchar(20)   NOT NULL,     -- denormalised (BR-63)
        inventory_item_id bigint        NULL
          REFERENCES inventory_items(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        description       text          NOT NULL DEFAULT '',
        quantity          numeric(14,3) NOT NULL DEFAULT 1,
        boxes             integer       NOT NULL DEFAULT 0,
        unit_price        numeric(14,2) NOT NULL,
        line_total        numeric(14,2) NOT NULL
          GENERATED ALWAYS AS (round(quantity * unit_price, 2)) STORED,

        CONSTRAINT fk_saleitem_item_type
          FOREIGN KEY (item_type_id, item_type_code) REFERENCES item_types(id, code)
          ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
        CONSTRAINT saleitem_quantity_positive CHECK (quantity > 0),
        CONSTRAINT saleitem_boxes_non_negative CHECK (boxes >= 0),
        CONSTRAINT saleitem_price_non_negative CHECK (unit_price >= 0),

        /**
         * BR-04 — the most valuable single constraint in the schema. A sale
         * line is genuinely two record shapes sharing a table: a stocked line
         * is a pointer into inventory, a machine line is free text. A machine
         * line that accidentally carried an inventory_item_id would be silently
         * deducted from stock at finalisation — real inventory disappearing
         * because of a bad row. This makes that state unrepresentable.
         *
         * Note what it does not forbid: a stocked line *may* carry a
         * description, and does in practice, so the invoice still reads
         * correctly if the product is later renamed. Only machine lines require
         * one.
         *
         * It still enumerates the two codes deliberately (FR-12.8.4): adding a
         * third row to item_types does not make it usable — any line using it
         * is rejected outright, which is correct, because an item type is a
         * discriminator between two differently *shaped* records, not a label.
         */
        CONSTRAINT saleitem_kind_consistent CHECK (
          (item_type_code = 'inventory'     AND inventory_item_id IS NOT NULL)
       OR (item_type_code = 'non_inventory' AND inventory_item_id IS NULL
                                            AND btrim(description) <> '')
        )
      )
    `);

    /**
     * Machine lines pass these untouched: a composite foreign key under the
     * default MATCH SIMPLE is not checked when any of its columns is NULL, and
     * a machine line has inventory_item_id IS NULL. So free-text lines are
     * exempt from the stock-shop rule without an exception written anywhere —
     * correct, since they draw on no stock at all. MATCH FULL would reject
     * them, and the difference is one keyword.
     */
    await queryRunner.query(`
      ALTER TABLE sale_items ADD CONSTRAINT fk_saleitem_sale_shop
        FOREIGN KEY (sale_id, shop_id) REFERENCES sales(id, shop_id)
        ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
    `);
    await queryRunner.query(`
      ALTER TABLE sale_items ADD CONSTRAINT fk_saleitem_inventory_shop
        FOREIGN KEY (inventory_item_id, shop_id) REFERENCES inventory_items(id, shop_id)
        ON UPDATE CASCADE ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
    `);

    await queryRunner.query(
      `CREATE INDEX idx_saleitem_sale ON sale_items (sale_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_saleitem_inventory ON sale_items (inventory_item_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_saleitem_type_sale ON sale_items (item_type_code, sale_id)`,
    );

    await queryRunner.query(`
      CREATE TABLE sale_payments (
        id                bigint        NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        sale_id           bigint        NOT NULL
          REFERENCES sales(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
        receipt_number    varchar(100)  NOT NULL UNIQUE,  -- RD-01 'RCPT-…'
        amount            numeric(14,2) NOT NULL,
        payment_date      date          NOT NULL,
        payment_method_id bigint        NOT NULL,          -- FR-12.9
        payment_scope     varchar(20)   NOT NULL DEFAULT 'customer',
        notes             text          NOT NULL DEFAULT '',
        created_at        timestamptz   NOT NULL DEFAULT now(),
        updated_at        timestamptz   NOT NULL DEFAULT now(),

        CONSTRAINT sale_payments_scope_pinned              -- BR-62
          CHECK (payment_scope = 'customer'),
        CONSTRAINT fk_sale_payments_method
          FOREIGN KEY (payment_method_id, payment_scope)
          REFERENCES payment_methods(id, scope)
          ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
        -- BR-10: '> 0' not '>= 0'. A zero payment produces a receipt number and
        -- a ledger line for no money, which is noise in an audit trail.
        CONSTRAINT salepayment_amount_positive CHECK (amount > 0)
      )
    `);
    await queryRunner.query(
      `CREATE INDEX idx_salepayment_sale ON sale_payments (sale_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_salepayment_date
         ON sale_payments (payment_date DESC, created_at DESC)`,
    );

    /**
     * FR-03.5 — one lump sum from a customer, spread oldest-first.
     *
     * The design decision worth recording is why the batch does not *replace*
     * the per-sale payments. BR-18 requires every sale's own payment history to
     * stay complete and independently printable, so the allocator creates a
     * real `sale_payments` row per sale touched — indistinguishable from a
     * payment entered directly — and the batch and allocation rows sit *above*
     * them as a record of the grouping.
     */
    await queryRunner.query(`
      CREATE TABLE customer_payment_batches (
        id                bigint        NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        customer_id       bigint        NOT NULL
          REFERENCES customers(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
        batch_ref         varchar(60)   NOT NULL UNIQUE,   -- RD-01 'CUSTPMT-…'
        payment_date      date          NOT NULL,
        payment_method_id bigint        NOT NULL,
        payment_scope     varchar(20)   NOT NULL DEFAULT 'customer',
        total_amount      numeric(14,2) NOT NULL,
        notes             text          NOT NULL DEFAULT '',
        created_by_id     bigint        NULL REFERENCES users(id) ON DELETE SET NULL,
        created_at        timestamptz   NOT NULL DEFAULT now(),

        CONSTRAINT batch_scope_pinned CHECK (payment_scope = 'customer'),
        CONSTRAINT fk_batch_method
          FOREIGN KEY (payment_method_id, payment_scope)
          REFERENCES payment_methods(id, scope)
          ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
        CONSTRAINT batch_amount_positive CHECK (total_amount > 0)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE customer_payment_allocations (
        id              bigint        NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        batch_id        bigint        NOT NULL
          REFERENCES customer_payment_batches(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
        sale_id         bigint        NOT NULL
          REFERENCES sales(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
        -- UNIQUE is what makes the 1:1 real (BR-18): a generated sale payment
        -- belongs to exactly one allocation, so it can never be double-counted
        -- across two batches.
        sale_payment_id bigint        NOT NULL UNIQUE
          REFERENCES sale_payments(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
        amount          numeric(14,2) NOT NULL,
        created_at      timestamptz   NOT NULL DEFAULT now(),

        CONSTRAINT allocation_amount_positive CHECK (amount > 0)
      )
    `);

    await queryRunner.query(
      `CREATE INDEX idx_batch_customer_created
         ON customer_payment_batches (customer_id, created_at DESC)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_allocation_batch ON customer_payment_allocations (batch_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_allocation_sale ON customer_payment_allocations (sale_id)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const table of [
      'customer_payment_allocations',
      'customer_payment_batches',
      'sale_payments',
      'sale_items',
      'sales',
    ]) {
      await queryRunner.query(`DROP TABLE IF EXISTS ${table}`);
    }
  }
}
