import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * FR-11 / DB_DESIGN.MD §4 — shops.
 *
 * Deliberately thin: a shop is a *scope* for other records rather than a record
 * with substance of its own. Two business fields and a status.
 *
 * There is no shop code, because sale and customer numbering stay on one
 * continuous global series (BR-46) rather than restarting per shop.
 *
 * Retirement is by `is_active`, not deletion: BR-48 makes RESTRICT the delete
 * rule on all three child tables, so any shop that has ever traded is
 * undeletable — as it should be, since deleting one would destroy its history.
 */
export class Shops1756000000004 implements MigrationInterface {
  name = 'Shops1756000000004';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE shops (
        id          bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name        varchar(200) NOT NULL,
        description text         NOT NULL DEFAULT '',
        is_active   boolean      NOT NULL DEFAULT true,
        created_at  timestamptz  NOT NULL DEFAULT now(),
        updated_at  timestamptz  NOT NULL DEFAULT now(),
        CONSTRAINT shop_name_not_blank CHECK (btrim(name) <> '')
      )
    `);

    // BR-47: 'Gulshan Branch' and 'gulshan branch' are the same shop.
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_shops_name_ci ON shops (lower(name))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS shops`);
  }
}
