import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * FR-05 / DB_DESIGN.MD §8 — suppliers, purchases, and supplier payments.
 *
 * Suppliers are **not** shop-scoped (FR-11.4): buying is done centrally for the
 * business, not per shop.
 *
 * `paid_amount` is derived, never entered (BR-28). It is a stored column rather
 * than a view for two reasons: the supplier list aggregates it across every
 * purchase on every page load, and materialising it is what allows BR-30 to be
 * a real CHECK constraint (`purchase_not_overpaid`) instead of a hope. The
 * rollup trigger in migration 014 is what keeps it true.
 */
export class Suppliers1756000000008 implements MigrationInterface {
  name = 'Suppliers1756000000008';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE suppliers (
        id         bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name       varchar(200) NOT NULL,
        address    text         NOT NULL DEFAULT '',
        phone      varchar(20)  NOT NULL,
        email      varchar(254) NOT NULL DEFAULT '',
        created_at timestamptz  NOT NULL DEFAULT now(),
        updated_at timestamptz  NOT NULL DEFAULT now(),
        CONSTRAINT supplier_name_not_blank CHECK (btrim(name) <> '')
      )
    `);

    await queryRunner.query(`
      CREATE TABLE supplier_purchases (
        id            bigint        NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        supplier_id   bigint        NOT NULL
          REFERENCES suppliers(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
        product_name  varchar(200)  NOT NULL,   -- free text, not an inventory link
        price         numeric(14,2) NOT NULL,
        paid_amount   numeric(14,2) NOT NULL DEFAULT 0,   -- derived (BR-28)
        purchase_date date          NOT NULL,
        notes         text          NOT NULL DEFAULT '',
        created_at    timestamptz   NOT NULL DEFAULT now(),
        updated_at    timestamptz   NOT NULL DEFAULT now(),

        CONSTRAINT purchase_price_non_negative CHECK (price >= 0),
        CONSTRAINT purchase_paid_non_negative  CHECK (paid_amount >= 0),
        -- BR-30 / BR-32: the cross-row rule made single-row by materialising
        -- the sum into paid_amount.
        CONSTRAINT purchase_not_overpaid CHECK (paid_amount <= price)
      )
    `);
    await queryRunner.query(
      `CREATE INDEX idx_purchase_supplier ON supplier_purchases (supplier_id)`,
    );
    // BR-31: supplier-level allocation walks purchases oldest-first.
    await queryRunner.query(
      `CREATE INDEX idx_purchase_fifo
         ON supplier_purchases (supplier_id, purchase_date, id)`,
    );

    await queryRunner.query(`
      CREATE TABLE supplier_purchase_payments (
        id                bigint        NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        purchase_id       bigint        NOT NULL
          REFERENCES supplier_purchases(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
        receipt_number    varchar(100)  NOT NULL UNIQUE,   -- RD-01 'SPAY-…'
        amount            numeric(14,2) NOT NULL,
        payment_date      date          NOT NULL,
        payment_method_id bigint        NOT NULL,          -- FR-12.9.2, RD-06
        payment_scope     varchar(20)   NOT NULL DEFAULT 'supplier',
        method_code       varchar(30)   NOT NULL,          -- denormalised (BR-64)
        reference_number  varchar(100)  NOT NULL DEFAULT '',
        notes             text          NOT NULL DEFAULT '',
        created_at        timestamptz   NOT NULL DEFAULT now(),
        updated_at        timestamptz   NOT NULL DEFAULT now(),

        CONSTRAINT supplierpayment_scope_pinned            -- BR-62
          CHECK (payment_scope = 'supplier'),
        CONSTRAINT fk_supplierpayment_method               -- BR-64
          FOREIGN KEY (payment_method_id, payment_scope, method_code)
          REFERENCES payment_methods(id, scope, code)
          ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
        CONSTRAINT supplierpayment_amount_positive CHECK (amount > 0),

        -- BR-29 — LC, cheque, TT and bank are traceable instruments and the
        -- reference number IS the trace. Cash has no instrument, so it needs
        -- none. Note this fails *closed*: an unfamiliar method code lands on
        -- the branch requiring a reference, which is the right default for a
        -- method nobody has written code for yet.
        CONSTRAINT supplierpayment_reference_required CHECK (
          method_code = 'cash' OR btrim(reference_number) <> ''
        )
      )
    `);
    await queryRunner.query(
      `CREATE INDEX idx_supplierpayment_purchase
         ON supplier_purchase_payments (purchase_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_supplierpayment_method
         ON supplier_purchase_payments (payment_method_id)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS supplier_purchase_payments`);
    await queryRunner.query(`DROP TABLE IF EXISTS supplier_purchases`);
    await queryRunner.query(`DROP TABLE IF EXISTS suppliers`);
  }
}
