import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * REQUIREMENTS.MD §10.3, option B — permissions attached to user types.
 *
 * §10.3 left the authorisation model open: Django's `auth_permission` and
 * `auth_group` do not exist under NestJS, and only the user *type* had a design.
 * Option B was chosen: a `permissions` catalogue and a `user_type_permissions`
 * join, so capability is a property of the type.
 *
 * The point of B over C is that there is **exactly one place to look** to find
 * out why someone can do something. FR-00.4.1 still holds — a user type
 * classifies the person, and the permissions it carries say what they may do —
 * but there is no second, competing grant mechanism per account.
 *
 * `codename` deliberately reuses the legacy names the requirements already cite
 * (`add_sale`, `finalize_sale`, `review_bills`, `change_expense`,
 * `view_reports_menu`, …) so every requirement stays traceable to the thing
 * that enforces it.
 */
export class Permissions1756000000003 implements MigrationInterface {
  name = 'Permissions1756000000003';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE permissions (
        id            bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        codename      varchar(100) NOT NULL,
        label         varchar(150) NOT NULL,
        -- Groups the permission on the administration screen ('sales',
        -- 'inventory', 'menu', …). Presentation only; nothing branches on it.
        module        varchar(50)  NOT NULL DEFAULT '',
        description   text         NOT NULL DEFAULT '',
        created_at    timestamptz  NOT NULL DEFAULT now(),
        CONSTRAINT permissions_codename_shape
          CHECK (codename ~ '^[a-z][a-z0-9_]*$')
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_permissions_codename ON permissions (codename)`,
    );

    await queryRunner.query(`
      CREATE TABLE user_type_permissions (
        user_type_id  bigint NOT NULL
          REFERENCES user_types(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
        permission_id bigint NOT NULL
          REFERENCES permissions(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
        PRIMARY KEY (user_type_id, permission_id)
      )
    `);
    await queryRunner.query(
      `CREATE INDEX idx_user_type_permissions_permission
         ON user_type_permissions (permission_id)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS user_type_permissions`);
    await queryRunner.query(`DROP TABLE IF EXISTS permissions`);
  }
}
