import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * FR-04 / DB_DESIGN.MD §5 — inventory and its movement log.
 *
 * Two independent stock dimensions: loose `quantity` (numeric, three decimals
 * for part units) and whole `box_count`. They are validated and deducted
 * separately at finalisation (BR-06) and recorded as separate movement rows
 * (BR-26), so the two can be audited independently.
 *
 * **BR-23 is the load-bearing constraint here.** Without `quantity >= 0` in the
 * database, a bug in the deduction path — or a hand-run UPDATE — drives stock
 * negative and every downstream valuation silently becomes wrong.
 *
 * **`part_code` is unique per shop, not globally (BR-51).** Under per-shop
 * stock, one physical product carried by three shops is three rows with three
 * quantities and three histories; forcing their codes to differ would be
 * absurd. The consequence to remember: a product code no longer identifies a
 * product — any lookup by `part_code` alone needs the shop too.
 */
export class Inventory1756000000009 implements MigrationInterface {
  name = 'Inventory1756000000009';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE inventory_items (
        id             bigint        NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        shop_id        bigint        NOT NULL           -- BR-49
          REFERENCES shops(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        part_code      varchar(50)   NOT NULL,          -- "Product Code"
        part_name      varchar(200)  NOT NULL,          -- "Product Name"
        description    text          NOT NULL DEFAULT '',
        location       varchar(100)  NOT NULL DEFAULT '',

        -- FR-12.4: category and supplier optional, unit required (FR-04.1.2)
        category_id    bigint        NULL
          REFERENCES categories(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        unit_id        bigint        NOT NULL
          REFERENCES units(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        -- FR-04.1.1: a real reference, not typed text. This closes D-05 and is
        -- the join that lets stock and purchasing be reported together.
        supplier_id    bigint        NULL
          REFERENCES suppliers(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,

        quantity       numeric(14,3) NOT NULL DEFAULT 0,  -- loose units
        box_count      integer       NOT NULL DEFAULT 0,  -- whole boxes
        purchase_price numeric(14,2) NULL,                -- cost   \\ kept apart so
        unit_price     numeric(14,2) NOT NULL DEFAULT 0,  -- selling /  margin stays visible (BR-22)
        minimum_stock  integer       NOT NULL DEFAULT 10,
        created_at     timestamptz   NOT NULL DEFAULT now(),
        updated_at     timestamptz   NOT NULL DEFAULT now(),

        CONSTRAINT inventoryitem_quantity_non_negative CHECK (quantity >= 0),
        CONSTRAINT inventoryitem_boxes_non_negative    CHECK (box_count >= 0),
        CONSTRAINT inventoryitem_minimum_non_negative  CHECK (minimum_stock >= 0),
        CONSTRAINT inventoryitem_prices_non_negative
          CHECK (unit_price >= 0 AND (purchase_price IS NULL OR purchase_price >= 0)),

        -- BR-51: two shops may each stock 'CLP-001'; one shop may not twice.
        CONSTRAINT uq_inventory_shop_part_code UNIQUE (shop_id, part_code),
        -- BR-50: composite target so a sale line can pin item and shop together
        CONSTRAINT uq_inventory_id_shop UNIQUE (id, shop_id)
      )
    `);

    await queryRunner.query(
      `CREATE INDEX idx_inventory_shop ON inventory_items (shop_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_inventory_category ON inventory_items (category_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_inventory_supplier ON inventory_items (supplier_id)`,
    );

    /**
     * BR-24 defines low stock as a column-to-column comparison, which an
     * ordinary index cannot serve — but a partial index whose predicate spans
     * columns of the same row can.
     *
     * `shop_id` leads deliberately: BR-52 evaluates low stock per shop, so the
     * common query is `WHERE shop_id = ? AND quantity <= minimum_stock`. A
     * business-wide count still uses it as an index-only scan of the whole
     * (small) index, so one index serves both the per-shop banner and the
     * aggregate dashboard. The banner on every page (FR-01.6) runs a COUNT
     * against this on every request, so it earns its keep immediately.
     */
    await queryRunner.query(
      `CREATE INDEX idx_inventory_low_stock_shop
         ON inventory_items (shop_id, id) WHERE quantity <= minimum_stock`,
    );

    /**
     * Append-only movement log (BR-25). Every row records before and after for
     * both dimensions, so any discrepancy is traceable to the action that
     * caused it.
     *
     * `created_by_id` is a real foreign key rather than the copied username
     * string §5 describes. That is hardening item H-13, closing deviation D-06
     * — movements would otherwise become unattributable if an account is
     * renamed. There is no legacy data here forcing the text fallback.
     */
    await queryRunner.query(`
      CREATE TABLE stock_histories (
        id                    bigint        NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        item_id               bigint        NOT NULL
          REFERENCES inventory_items(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
        transaction_type_id   bigint        NOT NULL     -- RD-07, FR-12.7
          REFERENCES transaction_types(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        quantity              numeric(14,3) NOT NULL,    -- units moved (absolute)
        previous_quantity     numeric(14,3) NOT NULL,
        new_quantity          numeric(14,3) NOT NULL,
        box_quantity          integer       NOT NULL DEFAULT 0,
        previous_box_quantity integer       NOT NULL DEFAULT 0,
        new_box_quantity      integer       NOT NULL DEFAULT 0,
        reason                text          NOT NULL DEFAULT '',
        created_at            timestamptz   NOT NULL DEFAULT now(),
        created_by_id         bigint        NULL         -- H-13, closes D-06
          REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,

        CONSTRAINT stockhistory_quantities_non_negative
          CHECK (quantity >= 0 AND previous_quantity >= 0 AND new_quantity >= 0)
      )
    `);

    await queryRunner.query(
      `CREATE INDEX idx_stockhistory_item_time
         ON stock_histories (item_id, created_at DESC)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_stockhistory_type ON stock_histories (transaction_type_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_stockhistory_created_by ON stock_histories (created_by_id)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS stock_histories`);
    await queryRunner.query(`DROP TABLE IF EXISTS inventory_items`);
  }
}
