import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * FR-10.1 — business name, logo, address, phone and email, configured centrally
 * and appearing across the interface and on every printed invoice and receipt.
 *
 * A singleton, like the two identifier counters: one business, one row, and a
 * `CHECK (id = 1)` that says so in the schema rather than leaving it a
 * convention in the code. A second row would mean two letterheads and no way to
 * say which is right.
 */
export class BusinessSettings1756000000017 implements MigrationInterface {
  name = 'BusinessSettings1756000000017';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE business_settings (
        id            bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name          varchar(200) NOT NULL DEFAULT 'Fashion Express',
        address       text         NOT NULL DEFAULT '',
        phone         varchar(40)  NOT NULL DEFAULT '',
        email         varchar(254) NOT NULL DEFAULT '',
        -- A relative path under the attachment root, or a data URI. The file
        -- itself is never stored in the database.
        logo          varchar(200) NULL,
        -- Free text printed at the foot of an invoice: terms, a thank-you.
        invoice_footer text        NOT NULL DEFAULT '',
        is_active     boolean      NOT NULL DEFAULT true,
        created_at    timestamptz  NOT NULL DEFAULT now(),
        updated_at    timestamptz  NOT NULL DEFAULT now(),
        created_by_id bigint       NULL
          REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
        updated_by_id bigint       NULL
          REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,

        CONSTRAINT businesssettings_singleton CHECK (id = 1),
        CONSTRAINT businesssettings_name_not_blank CHECK (btrim(name) <> '')
      )
    `);

    // The same touch trigger every other business table carries (migration 016).
    await queryRunner.query(`
      CREATE TRIGGER trg_business_settings_touch
          BEFORE UPDATE ON business_settings
          FOR EACH ROW EXECUTE FUNCTION fe_touch_updated_at();
    `);

    // Seeded so a printed document always has a letterhead, even before anyone
    // has visited the settings screen.
    await queryRunner.query(
      `INSERT INTO business_settings (id, name) OVERRIDING SYSTEM VALUE
       VALUES (1, 'Fashion Express')`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP TRIGGER IF EXISTS trg_business_settings_touch ON business_settings`,
    );
    await queryRunner.query(`DROP TABLE IF EXISTS business_settings`);
  }
}
