import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * better-auth's own tables, authored here rather than by `@better-auth/cli
 * migrate`.
 *
 * NFR-17 requires every schema change to arrive through a versioned, reversible
 * migration checked into the repository. The better-auth CLI's `migrate`
 * command writes DDL directly against the database, which would bypass that —
 * so the schema is written here, and `@better-auth/cli generate` is used only
 * to diff for drift after a better-auth upgrade.
 *
 * Column shapes follow better-auth 1.7.1's own table definitions
 * (`@better-auth/core/dist/db/get-tables.mjs`), with `casing: 'snake'` in the
 * adapter config mapping its camelCase field names onto these columns.
 *
 * `users` is not created here — it is the business table from migration 005,
 * which better-auth addresses via `user.modelName = 'users'`.
 */
export class AuthTables1756000000006 implements MigrationInterface {
  name = 'AuthTables1756000000006';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE sessions (
        id         bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        expires_at timestamptz  NOT NULL,
        token      varchar(255) NOT NULL,
        created_at timestamptz  NOT NULL DEFAULT now(),
        updated_at timestamptz  NOT NULL DEFAULT now(),
        ip_address varchar(100) NULL,
        user_agent text         NULL,
        user_id    bigint       NOT NULL
          REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_sessions_token ON sessions (token)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_sessions_user ON sessions (user_id)`,
    );
    // Expired-session sweeps and the "sign out everywhere" path both want this.
    await queryRunner.query(
      `CREATE INDEX idx_sessions_expires_at ON sessions (expires_at)`,
    );

    await queryRunner.query(`
      CREATE TABLE accounts (
        id                       bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        issuer                   varchar(255) NOT NULL,
        account_id               varchar(255) NOT NULL,
        provider_id              varchar(255) NOT NULL,
        user_id                  bigint       NOT NULL
          REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
        access_token             text         NULL,
        refresh_token            text         NULL,
        id_token                 text         NULL,
        access_token_expires_at  timestamptz  NULL,
        refresh_token_expires_at timestamptz  NULL,
        scope                    text         NULL,
        -- NFR-06: the salted, computationally expensive one-way hash (scrypt).
        password                 text         NULL,
        created_at               timestamptz  NOT NULL DEFAULT now(),
        updated_at               timestamptz  NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_accounts_issuer_account_id
         ON accounts (issuer, account_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_accounts_user ON accounts (user_id)`,
    );

    await queryRunner.query(`
      CREATE TABLE verifications (
        id         bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        identifier varchar(255) NOT NULL,
        value      text         NOT NULL,
        expires_at timestamptz  NOT NULL,
        created_at timestamptz  NOT NULL DEFAULT now(),
        updated_at timestamptz  NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(
      `CREATE INDEX idx_verifications_identifier ON verifications (identifier)`,
    );

    /**
     * FR-00.9 / FR-00.10 — login protection.
     *
     * better-auth's built-in rate limiter keys on IP + path. The requirement is
     * narrower and different: **5 consecutive failures for a given username +
     * IP combination**, refused for **1 hour**, and reset by a successful
     * sign-in. That cannot be expressed as a rate-limit rule, so it is tracked
     * here and enforced by hooks around the sign-in endpoint.
     *
     * The username is stored lower-cased so that `Rabby` and `rabby` share a
     * counter — otherwise the lockout is trivially side-stepped by changing
     * capitalisation.
     */
    await queryRunner.query(`
      CREATE TABLE login_attempts (
        id              bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        username        varchar(150) NOT NULL,
        ip_address      varchar(100) NOT NULL,
        failed_count    integer      NOT NULL DEFAULT 0,
        first_failed_at timestamptz  NOT NULL DEFAULT now(),
        last_failed_at  timestamptz  NOT NULL DEFAULT now(),
        locked_until    timestamptz  NULL,
        CONSTRAINT login_attempts_count_non_negative CHECK (failed_count >= 0)
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_login_attempts_username_ip
         ON login_attempts (lower(username), ip_address)`,
    );
    // Lets the periodic sweep drop expired lockouts cheaply.
    await queryRunner.query(
      `CREATE INDEX idx_login_attempts_locked_until
         ON login_attempts (locked_until) WHERE locked_until IS NOT NULL`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const table of [
      'login_attempts',
      'verifications',
      'accounts',
      'sessions',
    ]) {
      await queryRunner.query(`DROP TABLE IF EXISTS ${table}`);
    }
  }
}
