import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * FR-06, FR-07 / DB_DESIGN.MD §9 — expenses and bill claims.
 *
 * `expenses.shop_id` is the one addition to §9, implementing REQUIREMENTS.MD
 * §10.2. It is **nullable on purpose**: NULL means a business-wide cost that
 * belongs to no single shop — head office rent, the accountant's fee. Forcing
 * every expense onto a shop would be worse than not scoping them at all,
 * because it invites arbitrary allocation of costs that genuinely are shared.
 * With it, per-shop net profit becomes answerable; without it, only gross.
 *
 * FR-01.8 still applies to the dashboard: the expense and bill-claim tiles are
 * labelled to say which figures are business-wide.
 */
export class ExpensesAndClaims1756000000011 implements MigrationInterface {
  name = 'ExpensesAndClaims1756000000011';

  public async up(queryRunner: QueryRunner): Promise<void> {
    /**
     * Both classifications are references now (FR-12.10). The category is NOT
     * NULL and the payment method is not — which matches FR-06.1: every expense
     * is classified, but not every expense records an instrument.
     *
     * A nullable composite foreign key needs no special case. Under MATCH
     * SIMPLE it is not checked when any column is NULL, so `payment_scope`
     * stays pinned to 'expense' on every row while the reference stays
     * optional. Same mechanism that exempts machine lines in migration 010.
     *
     * No denormalised `method_code` here, unlike supplier payments: nothing
     * reads an expense's payment method — no BR-29 equivalent, no CHECK that
     * branches on it, no partial index over it. The copy would be pure cost.
     */
    await queryRunner.query(`
      CREATE TABLE expenses (
        id                  bigint        NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        date                date          NOT NULL,
        expense_category_id bigint        NOT NULL       -- FR-12.10.1, RD-05
          REFERENCES expense_categories(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        description         text          NOT NULL,
        amount              numeric(14,2) NOT NULL,
        paid_to             varchar(200)  NOT NULL DEFAULT '',
        receipt_number      varchar(100)  NOT NULL DEFAULT '',
        payment_method_id   bigint        NULL,          -- FR-12.10.3, optional
        payment_scope       varchar(20)   NOT NULL DEFAULT 'expense',
        notes               text          NOT NULL DEFAULT '',
        -- REQUIREMENTS.MD §10.2 — NULL means a business-wide cost.
        shop_id             bigint        NULL
          REFERENCES shops(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        created_at          timestamptz   NOT NULL DEFAULT now(),
        updated_at          timestamptz   NOT NULL DEFAULT now(),

        CONSTRAINT expenses_scope_pinned CHECK (payment_scope = 'expense'), -- BR-62
        CONSTRAINT fk_expenses_method
          FOREIGN KEY (payment_method_id, payment_scope)
          REFERENCES payment_methods(id, scope)
          ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
        CONSTRAINT expense_amount_non_negative CHECK (amount >= 0)
      )
    `);

    await queryRunner.query(
      `CREATE INDEX idx_expense_date ON expenses (date DESC, created_at DESC)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_expense_category ON expenses (expense_category_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_expense_method ON expenses (payment_method_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_expense_shop ON expenses (shop_id)`,
    );

    /**
     * `billclaim_review_consistent` makes BR-35 structural: a pending claim has
     * no reviewer, no review date and no expense; an approved one must have
     * both a review date and the expense it created (BR-36); a rejected one has
     * a review date and explicitly no expense (BR-37). "Cannot be processed
     * twice" then falls out for free.
     *
     * It enumerates the three codes deliberately (FR-12.11.2). Adding a fourth
     * row to the `claim` scope — say `on_hold` — does not make it usable: a
     * claim carrying it satisfies none of the branches and is rejected. A claim
     * state is a position in an approval workflow with obligations attached,
     * not a label.
     *
     * `user_id`, not `submitter_id` — and `ON DELETE RESTRICT`, not CASCADE.
     * That is hardening item H-12: CASCADE would destroy a person's entire
     * claim history the moment their account was deleted.
     */
    await queryRunner.query(`
      CREATE TABLE bill_claims (
        id             bigint        NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_id        bigint        NOT NULL          -- the staff member claiming
          REFERENCES users(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        amount         numeric(14,2) NOT NULL,
        description    text          NOT NULL,
        bill_date      date          NOT NULL,
        status_id      bigint        NOT NULL,          -- FR-12.11
        status_scope   varchar(20)   NOT NULL DEFAULT 'claim',
        status_code    varchar(30)   NOT NULL,          -- denormalised (BR-65)
        attachment     varchar(100)  NULL,              -- relative path (BR-34, NFR-11)
        approved_by_id bigint        NULL REFERENCES users(id) ON DELETE SET NULL,
        approval_date  date          NULL,
        expense_id     bigint        NULL REFERENCES expenses(id) ON DELETE SET NULL,
        created_at     timestamptz   NOT NULL DEFAULT now(),
        updated_at     timestamptz   NOT NULL DEFAULT now(),

        CONSTRAINT billclaims_status_scope_pinned CHECK (status_scope = 'claim'), -- BR-58
        CONSTRAINT fk_billclaims_status                                           -- BR-65
          FOREIGN KEY (status_id, status_scope, status_code)
          REFERENCES statuses(id, scope, code)
          ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
        CONSTRAINT billclaim_amount_positive CHECK (amount > 0),

        CONSTRAINT billclaim_review_consistent CHECK (
          (status_code = 'pending'  AND approved_by_id IS NULL
                                    AND approval_date IS NULL
                                    AND expense_id IS NULL)
       OR (status_code = 'approved' AND approval_date IS NOT NULL
                                    AND expense_id IS NOT NULL)
       OR (status_code = 'rejected' AND approval_date IS NOT NULL
                                    AND expense_id IS NULL)
        )
      )
    `);

    // An expense may back at most one claim. WHERE ... IS NOT NULL is required
    // because the vast majority of rows are pending and share a NULL.
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_billclaim_expense
         ON bill_claims (expense_id) WHERE expense_id IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_billclaim_user ON bill_claims (user_id, created_at DESC)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_billclaim_status ON bill_claims (status_code)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS bill_claims`);
    await queryRunner.query(`DROP TABLE IF EXISTS expenses`);
  }
}
