import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * FR-08 / DB_DESIGN.MD §10 — the ledger.
 *
 * Both classifications are references (FR-12.12), and neither is copied onto
 * the row. The rule from §23.1 decides it: carry a denormalised code only where
 * a CHECK or a partial index has to read it *locally*, and nothing here does.
 * `uq_ledger_source_reference` indexes `source_id` directly — a surrogate key
 * discriminates just as well as a string — and the balance is arithmetic over
 * `direction` rather than a comparison against the literal 'credit'.
 *
 * **`uq_ledger_source_reference` is the highest-priority item in DB_DESIGN.MD.**
 * BR-39 says the same payment cannot post twice. Enforced in application code
 * it is a read-then-write race: two concurrent transactions both SELECT, both
 * see nothing, both INSERT, and the result is a duplicated credit — money that
 * exists in the balance but not in reality, surfacing only when someone
 * reconciles by hand. The unique index removes the race entirely and lets the
 * write become `INSERT … ON CONFLICT DO NOTHING`, which is both correct and one
 * round trip instead of two. This closes deviation D-03.
 *
 * `WHERE reference <> ''` is required, not optional: this schema stores optional
 * text as the empty string (§1), so an unqualified unique index would collide
 * the moment two rows had a blank reference.
 */
export class Ledger1756000000012 implements MigrationInterface {
  name = 'Ledger1756000000012';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE ledger_entries (
        id            bigint        NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        timestamp     timestamptz   NOT NULL DEFAULT now(),
        entry_type_id bigint        NOT NULL          -- FR-12.12.1, RD-11
          REFERENCES ledger_entry_types(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        source_id     bigint        NOT NULL          -- FR-12.12.3, RD-11
          REFERENCES ledger_sources(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        reference     varchar(100)  NOT NULL DEFAULT '',
        description   text          NOT NULL DEFAULT '',
        amount        numeric(14,2) NOT NULL,

        CONSTRAINT ledger_amount_non_negative CHECK (amount >= 0)
      )
    `);

    // BR-39 — the constraint that makes double-posting impossible.
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_ledger_source_reference
         ON ledger_entries (source_id, reference) WHERE reference <> ''`,
    );

    await queryRunner.query(
      `CREATE INDEX idx_ledger_timestamp ON ledger_entries (timestamp DESC)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_ledger_entry_type ON ledger_entries (entry_type_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_ledger_source ON ledger_entries (source_id)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS ledger_entries`);
  }
}
