import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * FR-12 / DB_DESIGN.MD §23.1 — the business-managed vocabularies.
 *
 * These must exist before every table that references them, which is why they
 * are migration 001. §23 states the order explicitly: reference lists ->
 * statuses -> shops -> everything else.
 *
 * The shared shape is `code` (stable machine identifier, immutable under BR-59)
 * + `label` (freely editable) + `is_active` (retire without deleting, BR-60) +
 * `sort_order`. Lists that are purely names — job positions, departments,
 * categories — carry `name` alone, because there is no logic keyed on them and
 * nothing to keep stable.
 */
export class ReferenceLists1756000000001 implements MigrationInterface {
  name = 'ReferenceLists1756000000001';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // ---- user types (§23.1, RD-14) -------------------------------------
    // BR-56: privilege lives here and nowhere else. There is no is_superuser
    // or is_manager column on `users` to contradict it.
    await queryRunner.query(`
      CREATE TABLE user_types (
        id           bigint      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        code         varchar(30) NOT NULL,
        label        varchar(60) NOT NULL,
        description  text        NOT NULL DEFAULT '',
        is_superuser boolean     NOT NULL DEFAULT false,
        is_manager   boolean     NOT NULL DEFAULT false,
        sort_order   integer     NOT NULL DEFAULT 0,
        is_active    boolean     NOT NULL DEFAULT true,
        created_at   timestamptz NOT NULL DEFAULT now(),
        updated_at   timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT user_types_code_shape CHECK (code ~ '^[a-z][a-z0-9_]*$')
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_user_types_code ON user_types (code)`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_user_types_label_ci ON user_types (lower(label))`,
    );

    // ---- job positions and departments (FR-12.2) -----------------------
    await queryRunner.query(`
      CREATE TABLE job_positions (
        id         bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name       varchar(100) NOT NULL,
        is_active  boolean      NOT NULL DEFAULT true,
        created_at timestamptz  NOT NULL DEFAULT now(),
        updated_at timestamptz  NOT NULL DEFAULT now(),
        CONSTRAINT job_position_name_not_blank CHECK (btrim(name) <> '')
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_job_positions_name_ci ON job_positions (lower(name))`,
    );

    await queryRunner.query(`
      CREATE TABLE departments (
        id         bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name       varchar(100) NOT NULL,
        is_active  boolean      NOT NULL DEFAULT true,
        created_at timestamptz  NOT NULL DEFAULT now(),
        updated_at timestamptz  NOT NULL DEFAULT now(),
        CONSTRAINT department_name_not_blank CHECK (btrim(name) <> '')
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_departments_name_ci ON departments (lower(name))`,
    );

    // ---- product categories (FR-12.4.1) --------------------------------
    // Shared across shops: inventory is shop-scoped, its taxonomy is not.
    await queryRunner.query(`
      CREATE TABLE categories (
        id          bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name        varchar(100) NOT NULL,
        description text         NOT NULL DEFAULT '',
        is_active   boolean      NOT NULL DEFAULT true,
        created_at  timestamptz  NOT NULL DEFAULT now(),
        updated_at  timestamptz  NOT NULL DEFAULT now(),
        CONSTRAINT category_name_not_blank CHECK (btrim(name) <> '')
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_categories_name_ci ON categories (lower(name))`,
    );

    // ---- expense categories (FR-12.10, RD-05) --------------------------
    // Keeps a code although nothing branches on it: saved report filters are
    // written in terms of the codes, so relabelling must not re-file history.
    await queryRunner.query(`
      CREATE TABLE expense_categories (
        id         bigint      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        code       varchar(30) NOT NULL,
        label      varchar(60) NOT NULL,
        sort_order integer     NOT NULL DEFAULT 0,
        is_active  boolean     NOT NULL DEFAULT true,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT expense_categories_code_shape CHECK (code ~ '^[a-z][a-z0-9_]*$')
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_expense_categories_code ON expense_categories (code)`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_expense_categories_label_ci ON expense_categories (lower(label))`,
    );

    // ---- units (FR-12.4.2, RD-02) --------------------------------------
    await queryRunner.query(`
      CREATE TABLE units (
        id         bigint      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        code       varchar(20) NOT NULL,
        label      varchar(60) NOT NULL,
        sort_order integer     NOT NULL DEFAULT 0,
        is_active  boolean     NOT NULL DEFAULT true,
        CONSTRAINT units_code_shape CHECK (code ~ '^[a-z][a-z0-9_]*$')
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_units_code ON units (code)`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_units_label_ci ON units (lower(label))`,
    );

    // ---- stock movement types (FR-12.7, RD-07) -------------------------
    // `direction` moves the +/- presentation logic out of a template and into
    // data (FR-12.7.2). Structural list: labels editable, no add or delete
    // (BR-61) — enforced in the admin layer, since the rows are system-written.
    await queryRunner.query(`
      CREATE TABLE transaction_types (
        id         bigint      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        code       varchar(20) NOT NULL,
        label      varchar(60) NOT NULL,
        direction  smallint    NOT NULL,
        sort_order integer     NOT NULL DEFAULT 0,
        is_active  boolean     NOT NULL DEFAULT true,
        CONSTRAINT transaction_types_code_shape CHECK (code ~ '^[a-z][a-z0-9_]*$'),
        CONSTRAINT transaction_types_direction_valid CHECK (direction IN (-1, 0, 1))
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_transaction_types_code ON transaction_types (code)`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_transaction_types_label_ci ON transaction_types (lower(label))`,
    );

    // ---- sale line item types (FR-12.8.2) ------------------------------
    // The composite UNIQUE (id, code) is the target sale_items pins its
    // denormalised item_type_code against (BR-63).
    await queryRunner.query(`
      CREATE TABLE item_types (
        id         bigint      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        code       varchar(20) NOT NULL,
        label      varchar(60) NOT NULL,
        sort_order integer     NOT NULL DEFAULT 0,
        is_active  boolean     NOT NULL DEFAULT true,
        CONSTRAINT item_types_code_shape CHECK (code ~ '^[a-z][a-z0-9_]*$'),
        CONSTRAINT uq_item_types_id_code UNIQUE (id, code)
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_item_types_code ON item_types (code)`,
    );

    // ---- payment methods (FR-12.9, RD-04/RD-06/RD-15) ------------------
    // Three scopes keep LC off a customer receipt (BR-62). Two composite
    // targets because the consumers need different things: sale payments,
    // batches and expenses pin (id, scope); supplier payments also carry the
    // code, so they pin (id, scope, code) — BR-29 has to read it locally.
    await queryRunner.query(`
      CREATE TABLE payment_methods (
        id         bigint      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        scope      varchar(20) NOT NULL,
        code       varchar(30) NOT NULL,
        label      varchar(60) NOT NULL,
        sort_order integer     NOT NULL DEFAULT 0,
        is_active  boolean     NOT NULL DEFAULT true,
        CONSTRAINT payment_methods_scope_valid
          CHECK (scope IN ('customer','supplier','expense')),
        CONSTRAINT payment_methods_code_shape CHECK (code ~ '^[a-z][a-z0-9_]*$'),
        CONSTRAINT uq_payment_methods_scope_code UNIQUE (scope, code),
        CONSTRAINT uq_payment_methods_id_scope UNIQUE (id, scope),
        CONSTRAINT uq_payment_methods_id_scope_code UNIQUE (id, scope, code)
      )
    `);

    // ---- ledger entry types and sources (FR-12.12, RD-11) --------------
    // `direction` is the whole reason this list is a table: the running balance
    // becomes SUM(amount * direction) instead of a comparison against the
    // literal 'credit' (FR-12.12.2). Unlike transaction_types, 0 is refused —
    // a ledger line either raises the balance or lowers it.
    await queryRunner.query(`
      CREATE TABLE ledger_entry_types (
        id         bigint      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        code       varchar(20) NOT NULL,
        label      varchar(60) NOT NULL,
        direction  smallint    NOT NULL,
        sort_order integer     NOT NULL DEFAULT 0,
        is_active  boolean     NOT NULL DEFAULT true,
        CONSTRAINT ledger_entry_types_code_shape CHECK (code ~ '^[a-z][a-z0-9_]*$'),
        CONSTRAINT ledger_entry_types_direction_valid CHECK (direction IN (-1, 1))
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_ledger_entry_types_code ON ledger_entry_types (code)`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_ledger_entry_types_label_ci ON ledger_entry_types (lower(label))`,
    );

    await queryRunner.query(`
      CREATE TABLE ledger_sources (
        id         bigint      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        code       varchar(30) NOT NULL,
        label      varchar(60) NOT NULL,
        sort_order integer     NOT NULL DEFAULT 0,
        is_active  boolean     NOT NULL DEFAULT true,
        CONSTRAINT ledger_sources_code_shape CHECK (code ~ '^[a-z][a-z0-9_]*$')
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_ledger_sources_code ON ledger_sources (code)`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_ledger_sources_label_ci ON ledger_sources (lower(label))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const table of [
      'ledger_sources',
      'ledger_entry_types',
      'payment_methods',
      'item_types',
      'transaction_types',
      'units',
      'expense_categories',
      'categories',
      'departments',
      'job_positions',
      'user_types',
    ]) {
      await queryRunner.query(`DROP TABLE IF EXISTS ${table}`);
    }
  }
}
