import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * FR-12.3 / DB_DESIGN.MD §23.2 — one statuses list, four scopes.
 *
 * Staff have three statuses, customers two, sales four, bill claims three.
 * Putting them in one table is only safe because of the `scope` column plus the
 * composite-key technique: each consuming table pins `status_scope` to a
 * constant with a CHECK and references statuses by the pair. That is what stops
 * a customer being marked "On Leave" or a bill claim being marked "Finalized"
 * (BR-58).
 *
 * Two composite targets, for the same reason payment_methods has two:
 *  - `(id, scope)`       — users and customers. Nothing reads their code locally.
 *  - `(id, scope, code)` — sales (BR-63) and bill claims (BR-65), which carry a
 *    denormalised `status_code` because a CHECK or partial index has to read
 *    the value from the row it is checking and cannot join.
 */
export class Statuses1756000000002 implements MigrationInterface {
  name = 'Statuses1756000000002';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE statuses (
        id         bigint      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        scope      varchar(20) NOT NULL,
        code       varchar(30) NOT NULL,
        label      varchar(60) NOT NULL,
        sort_order integer     NOT NULL DEFAULT 0,
        is_active  boolean     NOT NULL DEFAULT true,

        CONSTRAINT statuses_scope_valid
          CHECK (scope IN ('user','customer','sale','claim')),
        CONSTRAINT statuses_code_shape CHECK (code ~ '^[a-z][a-z0-9_]*$'),
        CONSTRAINT uq_statuses_scope_code UNIQUE (scope, code),
        CONSTRAINT uq_statuses_id_scope UNIQUE (id, scope),
        CONSTRAINT uq_statuses_id_scope_code UNIQUE (id, scope, code)
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS statuses`);
  }
}
