import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * FR-03 / DB_DESIGN.MD §4 — customers.
 *
 * `customer_id` is the human-facing identifier and is immutable once assigned
 * (BR-45). It stays **globally** unique rather than per-shop: a customer number
 * identifies one party to the business, and two shops issuing `FE19082026-01`
 * to different people would make every receipt ambiguous. Contrast `part_code`
 * in the next migration, which deliberately goes the other way.
 *
 * `email` and `phone` are deliberately **not** unique — two branches of one
 * company share a phone number often enough that a constraint would block
 * legitimate records.
 *
 * `UNIQUE (id, shop_id)` looks redundant beside the primary key, and as a
 * constraint it is. Its purpose is to give `sales`' composite foreign key
 * something to reference (BR-53), since PostgreSQL requires a foreign key
 * target to be a declared unique or primary key.
 */
export class Customers1756000000007 implements MigrationInterface {
  name = 'Customers1756000000007';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE customers (
        id           bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        customer_id  varchar(50)  NOT NULL UNIQUE,   -- RD-01 'FE19082026-01'
        shop_id      bigint       NOT NULL           -- BR-49
          REFERENCES shops(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        name         varchar(200) NOT NULL,
        company      varchar(200) NOT NULL DEFAULT '',
        email        varchar(254) NOT NULL DEFAULT '',
        phone        varchar(20)  NOT NULL,
        address      text         NOT NULL DEFAULT '',
        city         varchar(100) NOT NULL DEFAULT '',
        status_id    bigint       NOT NULL,
        status_scope varchar(20)  NOT NULL DEFAULT 'customer',
        notes        text         NOT NULL DEFAULT '',
        created_at   timestamptz  NOT NULL DEFAULT now(),
        updated_at   timestamptz  NOT NULL DEFAULT now(),

        CONSTRAINT customer_name_not_blank CHECK (btrim(name) <> ''),
        -- BR-58: this row may only ever reference a customer-scoped status
        CONSTRAINT customers_status_scope_pinned CHECK (status_scope = 'customer'),
        CONSTRAINT fk_customers_status
          FOREIGN KEY (status_id, status_scope) REFERENCES statuses(id, scope)
          ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,

        -- BR-53: composite target so a sale can pin customer and shop together
        CONSTRAINT uq_customers_id_shop UNIQUE (id, shop_id)
      )
    `);

    await queryRunner.query(
      `CREATE INDEX idx_customer_status ON customers (status_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_customer_created ON customers (created_at DESC)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_customers_shop ON customers (shop_id)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS customers`);
  }
}
