import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * DB_DESIGN.MD §3 — login credentials and employment details on one record.
 *
 * The legacy system merged a separate Employee model into the user account and
 * that consolidation is kept: a staff member and a login are the same thing in
 * this business. Every attribution foreign key in the schema points here.
 *
 * **There are no privilege booleans on this table.** `is_superuser`,
 * `is_staff` and `is_manager` are gone (BR-56). Privilege belongs to the user's
 * *type* and is read by joining to it. `is_active` stays, because it answers a
 * different question — a type says what a person may do, `is_active` says
 * whether the account may authenticate at all. A suspended Owner is still an
 * Owner.
 *
 * **Two deviations from §3, both caused by better-auth owning identity:**
 *  - `password_hash` does not exist. The hash lives in `accounts.password`
 *    (scrypt), which satisfies NFR-06.
 *  - `name`, `email_verified`, `image` and `display_username` are added because
 *    better-auth's core schema and its username plugin require them.
 *    `first_name`/`last_name` remain the business columns.
 *
 * `shop_id` implements REQUIREMENTS.MD §10.1 option B (BR-55): the account's
 * home shop defaults the shop on every create form. It is nullable — head
 * office staff belong to no single shop — and it does **not** restrict what the
 * account can see. That was option C, and it is deliberately not built.
 */
export class Users1756000000005 implements MigrationInterface {
  name = 'Users1756000000005';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE users (
        id            bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

        -- authentication (better-auth core + username plugin)
        username         varchar(150) NOT NULL,
        display_username varchar(150) NULL,
        name             varchar(200) NOT NULL DEFAULT '',
        email            varchar(254) NOT NULL DEFAULT '',
        email_verified   boolean      NOT NULL DEFAULT false,
        image            text         NULL,

        first_name    varchar(150) NOT NULL DEFAULT '',
        last_name     varchar(150) NOT NULL DEFAULT '',
        is_active     boolean      NOT NULL DEFAULT true,
        last_login_at timestamptz  NULL,
        created_at    timestamptz  NOT NULL DEFAULT now(),
        updated_at    timestamptz  NOT NULL DEFAULT now(),

        -- employment (FR-00.6)
        employee_id   varchar(50)   NULL,        -- RD-01, generated on creation
        phone         varchar(20)   NOT NULL DEFAULT '',
        address       text          NOT NULL DEFAULT '',
        salary        numeric(14,2) NULL,
        join_date     date          NULL,
        notes         text          NOT NULL DEFAULT '',

        -- FR-12 reference data (§23)
        user_type_id    bigint      NOT NULL          -- BR-57: no untyped account
          REFERENCES user_types(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        job_position_id bigint      NULL              -- FR-12.2.2, optional
          REFERENCES job_positions(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        department_id   bigint      NULL              -- FR-12.2.2, optional
          REFERENCES departments(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        status_id       bigint      NOT NULL,
        status_scope    varchar(20) NOT NULL DEFAULT 'user',

        -- REQUIREMENTS.MD §10.1 option B (BR-55)
        shop_id         bigint      NULL
          REFERENCES shops(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,

        CONSTRAINT users_salary_non_negative
          CHECK (salary IS NULL OR salary >= 0),
        -- BR-58: this row may only ever reference a staff-scoped status
        CONSTRAINT users_status_scope_pinned CHECK (status_scope = 'user'),
        CONSTRAINT fk_users_status
          FOREIGN KEY (status_id, status_scope) REFERENCES statuses(id, scope)
          ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
      )
    `);

    // `username` is unique; the plugin normalises to lower case on write, so a
    // plain unique index is the right shape and `display_username` preserves
    // whatever casing the person typed.
    await queryRunner.query(
      `CREATE UNIQUE INDEX users_username_key ON users (username)`,
    );

    // `employee_id` is nullable but unique — PostgreSQL permits many NULLs in a
    // unique index, so an account created before one is issued does not collide.
    await queryRunner.query(
      `CREATE UNIQUE INDEX users_employee_id_key
         ON users (employee_id) WHERE employee_id IS NOT NULL`,
    );

    // Case-insensitive: 'Rabby@x.com' and 'rabby@x.com' are the same mailbox.
    // Partial, because email is optional and stored as '' when absent (§1).
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_users_email_ci ON users (lower(email)) WHERE email <> ''`,
    );

    await queryRunner.query(
      `CREATE INDEX idx_users_type ON users (user_type_id)`,
    );
    await queryRunner.query(`CREATE INDEX idx_users_shop ON users (shop_id)`);
    await queryRunner.query(
      `CREATE INDEX idx_users_status ON users (status_id)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS users`);
  }
}
